name: at_lorawan
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  args: ^2.4.0
  at_client: ^3.0.58
  at_cli_commons:
    path: ../../packages/at_cli_commons
  at_onboarding_cli: ^1.2.6
  at_utils: ^3.0.12
  chalkdart: ^2.0.9
  version: ^3.0.2
  logging: ^1.1.1
  path: ^1.8.3
  meta: ^1.9.1
  crypto: ^3.0.3


dependency_overrides:
  at_onboarding_cli:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_onboarding_cli
      ref: trunk
  at_client:
    path: ../../../at_client_sdk/packages/at_client

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
