name: at_lorawan
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.4.2
  at_client: ^3.0.62
  at_cli_commons: ^1.0.0
  at_onboarding_cli: ^1.3.0
  at_utils: ^3.0.15
  chalkdart: ^2.0.9
  version: ^3.0.2
  logging: ^1.2.0
  path: ^1.8.3
  meta: ^1.9.1
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
