name: at_lorawan
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.4.2
  at_client: ^3.0.60
  at_cli_commons:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_cli_commons
      ref: gkc-add-at_cli_commons
  at_onboarding_cli: ^1.3.0
  at_utils: ^3.0.13
  chalkdart: ^2.0.9
  version: ^3.0.2
  logging: ^1.2.0
  path: ^1.8.3
  meta: ^1.9.1
  crypto: ^3.0.3


dependency_overrides:
  at_onboarding_cli:
    git:
      url: https://github.com/atsign-foundation/at_libraries.git
      path: packages/at_onboarding_cli
      ref: registrar_api_update
  at_client:
    git:
      url: https://github.com/atsign-foundation/at_client_sdk.git
      path: packages/at_client
      ref: gkc-rpcs

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.3
