name: at_cli_commons
description: Library of useful stuff when building cli programs which use the atProtocol
version: 1.0.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  args: ^2.4.0
  at_client: ^3.0.58
  at_onboarding_cli: ^1.2.6
  at_utils: ^3.0.12
  chalkdart: ^2.0.9
  version: ^3.0.2
  logging: ^1.1.1
  meta: ^1.9.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
